# Generated by Django 4.1 on 2022-09-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prin_invest',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='contact_name',
            field=models.CharField(default='name', max_length=400),
        ),
    ]
