# Generated by Django 4.1 on 2022-09-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='eligible_age_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='post',
            name='eligible_age_min',
            field=models.IntegerField(default=0),
        ),
    ]
