# Generated by Django 4.1 on 2022-09-27 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_post_prin_invest_alter_post_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='no_participants',
            field=models.ManyToManyField(blank=True, related_name='ct_no_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
