# Generated by Django 4.1 on 2022-09-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_eligible_age_max_post_eligible_age_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.IntegerField(choices=[(0, 'All'), (1, 'Male'), (2, 'Female')], default=0),
        ),
    ]
