# Generated by Django 4.1 on 2022-09-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_excerpt_post_irb_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contact_email',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='contact_name',
            field=models.CharField(default='xy@ct.com', max_length=400),
        ),
        migrations.AlterField(
            model_name='post',
            name='end_dt',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_dt',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
