# Generated by Django 4.1 on 2022-10-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='primary_disease',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
