# Generated by Django 4.1 on 2022-11-07 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_primary_disease'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
